apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuralretail.fullname" . }}-fastapi
  labels:
    app.kubernetes.io/name: {{ include "neuralretail.name" . }}
    app.kubernetes.io/component: fastapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "neuralretail.name" . }}
    app.kubernetes.io/component: fastapi
---
{{- if .Values.streamlit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuralretail.fullname" . }}-streamlit
  labels:
    app.kubernetes.io/name: {{ include "neuralretail.name" . }}
    app.kubernetes.io/component: streamlit
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.streamlit.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "neuralretail.name" . }}
    app.kubernetes.io/component: streamlit
{{- end }}
